import Navigation from "@/app/_components/Navigation";
import {Logo} from "@/app/_components/Logo";
import "@/app/_styles/globals.css";

export const metadata = {
  title: 'The Wild Oasis',
  description: 'Generated by Next.js',
  keywords: 'NEXTJS Application',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-blue-900 min-h-screen text-primary-100`}>
        <div id="wrapper">
          <header>
            <Logo />
            <Navigation />
          </header>
          <main>
            {children}
          </main>
          <footer>Copyrights by The Wild Oasis</footer>
        </div>
      </body>
    </html>
  )
}
